// Mock data for development — replaced with Supabase when keys are provided
import type { Listing, Order, Restaurant, Transaction } from '../types';

const now = new Date();
const tonight = new Date(now);
tonight.setHours(20, 0, 0, 0);

const expiresAt = new Date(tonight);
expiresAt.setHours(21, 30, 0, 0);

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-001',
    owner_id: 'owner-001',
    name: 'Mama Put Palace',
    description: 'The best Nigerian home-cooked meals in Lagos Island',
    address: '14 Mireni Rd, Lagos Island',
    area: 'Lagos Island',
    city: 'Lagos',
    latitude: 6.4531,
    longitude: 3.3958,
    is_verified: true,
    is_active: true,
    is_live_tonight: true,
    restaurant_wallet_balance: 142000,
    total_meals_saved: 847,
    total_revenue_recovered: 1284000,
    total_co2_diverted_kg: 423.5,
    rating: 4.8,
    rating_count: 312,
    restaurant_type: 'Traditional Nigerian',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'rest-002',
    owner_id: 'owner-002',
    name: 'The Kitchen Lab',
    description: 'Modern fusion cuisine meeting African flavors with gourmet techniques',
    address: '7 Drake Street, Lekki',
    area: 'Lekki',
    city: 'Lagos',
    latitude: 6.4698,
    longitude: 3.5852,
    is_verified: true,
    is_active: true,
    is_live_tonight: true,
    restaurant_wallet_balance: 89500,
    total_meals_saved: 523,
    total_revenue_recovered: 876000,
    total_co2_diverted_kg: 261.5,
    rating: 4.6,
    rating_count: 198,
    restaurant_type: 'Fusion',
    created_at: '2024-02-10T00:00:00Z',
  },
  {
    id: 'rest-003',
    owner_id: 'owner-003',
    name: "Che-Che's Buka",
    description: 'Local delicacies and street food with a homely touch',
    address: '22 Ideli Crescent, Victoria Island',
    area: 'Victoria Island',
    city: 'Lagos',
    latitude: 6.4281,
    longitude: 3.4219,
    is_verified: true,
    is_active: true,
    is_live_tonight: true,
    restaurant_wallet_balance: 67200,
    total_meals_saved: 391,
    total_revenue_recovered: 542000,
    total_co2_diverted_kg: 195.5,
    rating: 4.9,
    rating_count: 445,
    restaurant_type: 'Local Buka',
    created_at: '2024-03-05T00:00:00Z',
  },
  {
    id: 'rest-004',
    owner_id: 'owner-004',
    name: "Nami's Kitchen",
    description: 'Authentic continental dishes made for the Lagos palate',
    address: '45 Ikeja Rd, Ikeja',
    area: 'Ikeja',
    city: 'Lagos',
    latitude: 6.6018,
    longitude: 3.3515,
    is_verified: true,
    is_active: true,
    is_live_tonight: false,
    restaurant_wallet_balance: 34800,
    total_meals_saved: 214,
    total_revenue_recovered: 298000,
    total_co2_diverted_kg: 107.0,
    rating: 4.5,
    rating_count: 87,
    restaurant_type: 'Continental',
    created_at: '2024-04-20T00:00:00Z',
  },
  {
    id: 'rest-005',
    owner_id: 'owner-005',
    name: 'Street Sizzle',
    description: 'Premium street food — Suya, shawarma, chicken',
    address: '8 Bade St, Surulere',
    area: 'Surulere',
    city: 'Lagos',
    latitude: 6.4969,
    longitude: 3.3486,
    is_verified: true,
    is_active: true,
    is_live_tonight: true,
    restaurant_wallet_balance: 56100,
    total_meals_saved: 678,
    total_revenue_recovered: 891000,
    total_co2_diverted_kg: 339.0,
    rating: 4.7,
    rating_count: 521,
    restaurant_type: 'Street Food',
    created_at: '2024-01-28T00:00:00Z',
  },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'lst-001',
    restaurant_id: 'rest-001',
    food_name: 'Jollof Rice + Fried Chicken',
    food_category: 'rice',
    description: 'Party-style jollof rice cooked over open flame, served with 2 pieces of fried chicken and plantain',
    original_price: 2800,
    current_price: 1200,
    discount_percent: 57,
    portions_total: 5,
    portions_remaining: 3,
    is_last_one: false,
    status: 'live',
    goes_live_at: tonight.toISOString(),
    expires_at: expiresAt.toISOString(),
    allergen_note: 'Contains gluten',
    restaurant: MOCK_RESTAURANTS[0],
    created_at: tonight.toISOString(),
  },
  {
    id: 'lst-002',
    restaurant_id: 'rest-001',
    food_name: 'Eba and Egusi Soup',
    food_category: 'soup',
    description: 'Homemade eba with rich egusi soup, goat meat, fish, and fresh vegetables',
    original_price: 1500,
    current_price: 700,
    discount_percent: 53,
    portions_total: 4,
    portions_remaining: 2,
    is_last_one: false,
    status: 'live',
    goes_live_at: tonight.toISOString(),
    expires_at: expiresAt.toISOString(),
    restaurant: MOCK_RESTAURANTS[0],
    created_at: tonight.toISOString(),
  },
  {
    id: 'lst-003',
    restaurant_id: 'rest-002',
    food_name: 'Shawarma Box (3pcs)',
    food_category: 'chicken',
    description: 'Juicy chicken shawarma wrapped in soft lavash bread, topped with special sauce and vegetables',
    original_price: 3500,
    current_price: 1500,
    discount_percent: 57,
    portions_total: 6,
    portions_remaining: 5,
    is_last_one: false,
    status: 'live',
    goes_live_at: tonight.toISOString(),
    expires_at: expiresAt.toISOString(),
    restaurant: MOCK_RESTAURANTS[1],
    created_at: tonight.toISOString(),
  },
  {
    id: 'lst-004',
    restaurant_id: 'rest-002',
    food_name: 'Grilled Tilapia + Plantain',
    food_category: 'other',
    description: 'Fresh Tilapia grilled with herbs, served with sweet fried plantain and pepper sauce',
    original_price: 4200,
    current_price: 1800,
    discount_percent: 57,
    portions_total: 3,
    portions_remaining: 1,
    is_last_one: true,
    status: 'live',
    goes_live_at: tonight.toISOString(),
    expires_at: expiresAt.toISOString(),
    restaurant: MOCK_RESTAURANTS[1],
    created_at: tonight.toISOString(),
  },
  {
    id: 'lst-005',
    restaurant_id: 'rest-003',
    food_name: 'Puff Puff + Peppered Gizzard',
    food_category: 'snacks',
    description: 'Fresh fried puff puff balls paired with fiery peppered gizzard — the perfect Nigerian snack',
    original_price: 2200,
    current_price: 900,
    discount_percent: 59,
    portions_total: 8,
    portions_remaining: 4,
    is_last_one: false,
    status: 'live',
    goes_live_at: tonight.toISOString(),
    expires_at: expiresAt.toISOString(),
    restaurant: MOCK_RESTAURANTS[2],
    created_at: tonight.toISOString(),
  },
  {
    id: 'lst-006',
    restaurant_id: 'rest-003',
    food_name: 'Ofada Rice + Ayamase Stew',
    food_category: 'rice',
    description: 'Aromatic ofada rice served with homemade ayamase stew made with special pepper blend',
    original_price: 2500,
    current_price: 1100,
    discount_percent: 56,
    portions_total: 4,
    portions_remaining: 2,
    is_last_one: false,
    status: 'live',
    goes_live_at: tonight.toISOString(),
    expires_at: expiresAt.toISOString(),
    restaurant: MOCK_RESTAURANTS[2],
    created_at: tonight.toISOString(),
  },
  {
    id: 'lst-007',
    restaurant_id: 'rest-005',
    food_name: 'Suya Platter (500g)',
    food_category: 'chicken',
    description: 'Premium beef suya marinated in special spice blend, grilled to perfection over charcoal',
    original_price: 5000,
    current_price: 2200,
    discount_percent: 56,
    portions_total: 3,
    portions_remaining: 1,
    is_last_one: true,
    status: 'live',
    goes_live_at: tonight.toISOString(),
    expires_at: expiresAt.toISOString(),
    restaurant: MOCK_RESTAURANTS[4],
    created_at: tonight.toISOString(),
  },
  {
    id: 'lst-008',
    restaurant_id: 'rest-005',
    food_name: 'Moi Moi + Efo Riro',
    food_category: 'other',
    description: 'Homemade Moi Moi packets served with sweet efo riro vegetable soup',
    original_price: 1800,
    current_price: 800,
    discount_percent: 56,
    portions_total: 6,
    portions_remaining: 3,
    is_last_one: false,
    status: 'live',
    goes_live_at: tonight.toISOString(),
    expires_at: expiresAt.toISOString(),
    restaurant: MOCK_RESTAURANTS[4],
    created_at: tonight.toISOString(),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-001',
    customer_id: 'user-001',
    listing_id: 'lst-003',
    restaurant_id: 'rest-002',
    quantity: 2,
    unit_price: 1500,
    total_amount: 3000,
    payment_method: 'wallet',
    payment_status: 'paid',
    payment_reference: 'PAY-1234567',
    qr_payload: 'eyJvcmRlcl9pZCI6Im9yZC0wMDEiLCJjb2xsZWN0aW9uX2NvZGUiOiJDUS1BQUE1NSIsImV4cGlyZXNfYXQiOiIyMDI2LTA1LTExVDIxOjMwOjAwLjAwMFoifQ',
    collection_code: 'CQ-AAA55',
    order_status: 'confirmed',
    expires_at: expiresAt.toISOString(),
    created_at: tonight.toISOString(),
    restaurant: MOCK_RESTAURANTS[1],
    listing: MOCK_LISTINGS[2],
  },
  {
    id: 'ord-002',
    customer_id: 'user-001',
    listing_id: 'lst-001',
    restaurant_id: 'rest-001',
    quantity: 1,
    unit_price: 1200,
    total_amount: 1200,
    payment_method: 'wallet',
    payment_status: 'paid',
    payment_reference: 'PAY-7654321',
    collection_code: 'CQ-BBB22',
    order_status: 'collected',
    collected_at: new Date(Date.now() - 86400000).toISOString(),
    expires_at: new Date(Date.now() - 72000000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    restaurant: MOCK_RESTAURANTS[0],
    listing: MOCK_LISTINGS[0],
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn-001',
    user_id: 'user-001',
    type: 'order_payment',
    amount: -3000,
    balance_after: 12000,
    description: 'Order payment — Shawarma Box x2',
    reference: 'PAY-1234567',
    created_at: tonight.toISOString(),
  },
  {
    id: 'txn-002',
    user_id: 'user-001',
    type: 'wallet_credit',
    amount: 10000,
    balance_after: 15000,
    description: 'Wallet funding via Paystack',
    reference: 'FUND-0987654',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'txn-003',
    user_id: 'user-001',
    type: 'order_payment',
    amount: -1200,
    balance_after: 5000,
    description: 'Order payment — Jollof Rice + Chicken x1',
    reference: 'PAY-7654321',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'txn-004',
    user_id: 'user-001',
    type: 'referral_bonus',
    amount: 500,
    balance_after: 6200,
    description: 'Referral bonus — friend joined ChopQuick',
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
];
