kind = "mobile"
previewPath = "/"
title = "ChopQuick"
version = "1.0.0"
id = "artifacts/chopquick"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18895

[services.development]
run = "pnpm --filter @workspace/chopquick run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/chopquick", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/chopquick", "run", "serve" ]

[services.env]
PORT = "18895"
BASE_PATH = "/"
